name: Daily Proxy Update & High-Speed Test

on:
  schedule:
    # Запуск каждый день в 5:00 утра по Москве (2:00 ночи по UTC)
    - cron: '0 2 * * *'
  workflow_dispatch: # Позволяет запускать проверку вручную кнопкой в интерфейсе

jobs:
  run-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4.2.2

      - name: Set up Python Environment
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.x'

      - name: Execute High-Speed Aggregator Script
        # ДИРЕКТИВА ДЛЯ ВЫВОДА ЛОГОВ В РЕАЛЬНОМ ВРЕМЕНИ
        env:
          PYTHONUNBUFFERED: "1"
        run: python update_proxies.py

      - name: Commit and Push Verified Subscriptions
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add *.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update verified proxies $(date +'%Y-%m-%d')" && git push)
